from __future__ import annotations

import os
import tempfile
from pathlib import Path

from gx3cli.gx3_report_issue import build_issue_body, main
from gx3cli.gx3_support_bundle import build_bundle


def test_issue_body_redacts_user_text_and_error_details() -> None:
    old_cwd = Path.cwd()
    with tempfile.TemporaryDirectory(prefix="gx3_report_issue_") as tmp:
        os.chdir(tmp)
        try:
            root = Path(tmp) / "秘密プロジェクト"
            root.mkdir()
            bundle = Path(tmp) / "support.zip"
            build_bundle(root, bundle)
            sample_ip = ".".join(["192", "168", "0", "10"])

            body = build_issue_body(
                root,
                bundle,
                command="gx3-cli trace-device M100 --root C:\\Projects\\秘密プロジェクト",
                message="設備起動が解析できない",
                error_text=f"{sample_ip} でエラー",
            )
        finally:
            os.chdir(old_cwd)

    assert "Generated by gx3-cli report-issue" in body
    assert sample_ip not in body
    assert "秘密プロジェクト" not in body
    assert "設備起動" not in body


def test_dry_run_creates_bundle_and_issue_body_without_submit() -> None:
    old_cwd = Path.cwd()
    with tempfile.TemporaryDirectory(prefix="gx3_report_issue_") as tmp:
        os.chdir(tmp)
        try:
            root = Path(tmp) / "project"
            root.mkdir()
            bundle = Path(tmp) / "support.zip"
            body = Path(tmp) / "issue.md"

            code = main(
                [
                    "--root",
                    str(root),
                    "-o",
                    str(bundle),
                    "--body-output",
                    str(body),
                    "--message",
                    "cannot parse project",
                    "--dry-run",
                ]
            )
            assert code == 0
            assert bundle.exists()
            assert body.exists()
            assert "Support Request" in body.read_text(encoding="utf-8")
        finally:
            os.chdir(old_cwd)


def main_test() -> int:
    test_issue_body_redacts_user_text_and_error_details()
    test_dry_run_creates_bundle_and_issue_body_without_submit()
    print("report issue checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main_test())
