"""Write-target operand positions, taken from the instruction manuals.

Generated data. Each entry maps an opcode to {operand count: indices written},
where the index is the 0-based position of the operand in the ladder
instruction. Only the positions are recorded here -- no manual text.

Source: the operand tables ("内容，範囲，データ型") of
  - MELSEC iQ-R Programming Manual (CPU Module Instructions, Standard
    Functions/Function Blocks)            SH-081226-AF
  - MELSEC iQ-R Programming Manual (Module Dedicated Instructions)
    ................................      SH-081975-R
  - MELSEC iQ-R Programming Manual (Process Control Function Blocks/
    Instructions)                         SH-081748-O
  - MELSEC iQ-R Ethernet User's Manual (Application)  SH-081253-AI

The manuals name every operand: (d), (d1), (d2) are the destinations, (s*) the
sources, (n*) counts, (U) the module head I/O number. The destinations are what
this table records. EN/ENO are FBD/LD-only pins and are not ladder operands, so
they are excluded from the operand count and from the indices.

Keyed by operand count because several instructions take a different number of
operands with different destinations -- WAND with 2 operands writes its second,
with 3 operands its third.

Do not hand-edit. Regenerate from the manual operand tables when a manual
revision changes an instruction.
"""

from __future__ import annotations

MANUAL_WRITE_ARGS: dict[str, dict[int, tuple[int, ...]]] = {
    '$+': {2: (1,), 3: (2,)},
    '$+P': {2: (1,), 3: (2,)},
    '$MOV': {2: (1,)},
    '$MOVP': {2: (1,)},
    'ACOS': {2: (1,)},
    'ACOSD': {2: (1,)},
    'ACOSDP': {2: (1,)},
    'ACOSP': {2: (1,)},
    'ADRSET': {2: (1,)},
    'ADRSETP': {2: (1,)},
    'ASC2INT': {3: (1,)},
    'ASC2INTP': {3: (1,)},
    'ASIN': {2: (1,)},
    'ASIND': {2: (1,)},
    'ASINDP': {2: (1,)},
    'ASINP': {2: (1,)},
    'ATAN': {2: (1,)},
    'ATAND': {2: (1,)},
    'ATANDP': {2: (1,)},
    'ATANP': {2: (1,)},
    'B*': {3: (2,)},
    'B*P': {3: (2,)},
    'B+': {2: (1,), 3: (2,)},
    'B+P': {2: (1,), 3: (2,)},
    'B-': {2: (1,), 3: (2,)},
    'B-P': {2: (1,), 3: (2,)},
    'B/': {3: (2,)},
    'B/P': {3: (2,)},
    'BACOS': {2: (1,)},
    'BACOSP': {2: (1,)},
    'BASIN': {2: (1,)},
    'BASINP': {2: (1,)},
    'BATAN': {2: (1,)},
    'BATANP': {2: (1,)},
    'BCD': {2: (1,)},
    'BCDDA': {2: (1,)},
    'BCDDAP': {2: (1,)},
    'BCDP': {2: (1,)},
    'BCOS': {2: (1,)},
    'BCOSP': {2: (1,)},
    'BDSQRT': {2: (1,)},
    'BDSQRTP': {2: (1,)},
    'BIN': {2: (1,)},
    'BINHA': {2: (1,)},
    'BINHAP': {2: (1,)},
    'BINP': {2: (1,)},
    'BKAND': {4: (2,)},
    'BKANDP': {4: (2,)},
    'BKBCD': {3: (1,)},
    'BKBCDP': {3: (1,)},
    'BKBIN': {3: (1,)},
    'BKBINP': {3: (1,)},
    'BKOR': {4: (2,)},
    'BKORP': {4: (2,)},
    'BKRST': {2: (0,)},
    'BKRSTP': {2: (0,)},
    'BKXNR': {4: (2,)},
    'BKXNRP': {4: (2,)},
    'BKXOR': {4: (2,)},
    'BKXORP': {4: (2,)},
    'BLKMOVB': {3: (1,)},
    'BLKMOVBP': {3: (1,)},
    'BMOV': {3: (1,)},
    'BMOVL': {3: (1,)},
    'BMOVLP': {3: (1,)},
    'BMOVP': {3: (1,)},
    'BON': {3: (1,)},
    'BONP': {3: (1,)},
    'BREAK': {2: (0,)},
    'BREAKP': {2: (0,)},
    'BRSET': {1: ()},
    'BRST': {2: (0,)},
    'BRSTP': {2: (0,)},
    'BSET': {2: (0,)},
    'BSETP': {2: (0,)},
    'BSFL': {2: (0,)},
    'BSFLP': {2: (0,)},
    'BSFR': {2: (0,)},
    'BSFRP': {2: (0,)},
    'BSIN': {2: (1,)},
    'BSINP': {2: (1,)},
    'BSQRT': {2: (1,)},
    'BSQRTP': {2: (1,)},
    'BTAN': {2: (1,)},
    'BTANP': {2: (1,)},
    'BTOW': {3: (1,)},
    'BTOWP': {3: (1,)},
    'BXCH': {3: (0, 1)},
    'BXCHP': {3: (0, 1)},
    'CALL': {2: ()},
    'CALLP': {2: ()},
    'CCD': {3: (1,)},
    'CCDP': {3: (1,)},
    'CML': {2: (1,)},
    'CMLB': {2: (1,)},
    'CMLBP': {2: (1,)},
    'CMLP': {2: (1,)},
    'CONTWR': {4: (2, 3)},
    'CONTWRP': {4: (2, 3)},
    'COS': {2: (1,)},
    'COSD': {2: (1,)},
    'COSDP': {2: (1,)},
    'COSP': {2: (1,)},
    'CRC': {3: (1,)},
    'CRCP': {3: (1,)},
    'DABCD': {2: (1,)},
    'DABCDP': {2: (1,)},
    'DAND': {2: (1,), 3: (2,)},
    'DANDP': {2: (1,), 3: (2,)},
    'DATATRG': {1: ()},
    'DATE+': {3: (2,)},
    'DATE+P': {3: (2,)},
    'DATE-': {3: (2,)},
    'DATE-P': {3: (2,)},
    'DATERD': {1: (0,)},
    'DATERDP': {1: (0,)},
    'DATEWR': {1: ()},
    'DATEWRP': {1: ()},
    'DB*': {3: (2,)},
    'DB*P': {3: (2,)},
    'DB+': {2: (1,), 3: (2,)},
    'DB+P': {2: (1,), 3: (2,)},
    'DB-': {2: (1,), 3: (2,)},
    'DB-P': {2: (1,), 3: (2,)},
    'DB/': {3: (2,)},
    'DB/P': {3: (2,)},
    'DBCD': {2: (1,)},
    'DBCDDA': {2: (1,)},
    'DBCDDAP': {2: (1,)},
    'DBCDP': {2: (1,)},
    'DBCLOSE': {3: (1, 2)},
    'DBCLOSEP': {3: (1, 2)},
    'DBCOMMIT': {3: (1, 2)},
    'DBCOMMITP': {3: (1, 2)},
    'DBDELETE': {5: (3, 4)},
    'DBDELETEP': {5: (3, 4)},
    'DBEXPORT': {3: (1, 2)},
    'DBEXPORTP': {3: (1, 2)},
    'DBIMPORT': {3: (1, 2)},
    'DBIMPORTP': {3: (1, 2)},
    'DBIN': {2: (1,)},
    'DBINHA': {2: (1,)},
    'DBINHAP': {2: (1,)},
    'DBINP': {2: (1,)},
    'DBINSERT': {6: (4, 5)},
    'DBINSERTP': {6: (4, 5)},
    'DBL2DINT': {2: (1,)},
    'DBL2DINTP': {2: (1,)},
    'DBL2FLT': {2: (1,)},
    'DBL2FLTP': {2: (1,)},
    'DBL2INT': {2: (1,)},
    'DBL2INTP': {2: (1,)},
    'DBL2UDINT': {2: (1,)},
    'DBL2UDINTP': {2: (1,)},
    'DBL2UINT': {2: (1,)},
    'DBL2UINTP': {2: (1,)},
    'DBON': {3: (1,)},
    'DBONP': {3: (1,)},
    'DBOPEN': {4: (1, 2, 3)},
    'DBOPENP': {4: (1, 2, 3)},
    'DBROLBAK': {3: (1, 2)},
    'DBROLBAKP': {3: (1, 2)},
    'DBSELECT': {7: (4, 5, 6)},
    'DBSELECTP': {7: (4, 5, 6)},
    'DBTRANS': {3: (1, 2)},
    'DBTRANSP': {3: (1, 2)},
    'DBUPDATE': {7: (5, 6)},
    'DBUPDATEP': {7: (5, 6)},
    'DCML': {2: (1,)},
    'DCMLP': {2: (1,)},
    'DDABCD': {2: (1,)},
    'DDABCDP': {2: (1,)},
    'DDSFL': {2: (0,)},
    'DDSFLP': {2: (0,)},
    'DDSFR': {2: (0,)},
    'DDSFRP': {2: (0,)},
    'DECO': {3: (1,)},
    'DECOP': {3: (1,)},
    'DEG': {2: (1,)},
    'DEGD': {2: (1,)},
    'DEGDP': {2: (1,)},
    'DEGP': {2: (1,)},
    'DELTA': {1: (0,)},
    'DELTAP': {1: (0,)},
    'DFMOV': {3: (1,)},
    'DFMOVL': {3: (1,)},
    'DFMOVLP': {3: (1,)},
    'DFMOVP': {3: (1,)},
    'DHABIN': {2: (1,)},
    'DHABINP': {2: (1,)},
    'DHOURM': {3: (1, 2)},
    'DI': {1: ()},
    'DINT2DBL': {2: (1,)},
    'DINT2DBLP': {2: (1,)},
    'DINT2FLT': {2: (1,)},
    'DINT2FLTP': {2: (1,)},
    'DINT2INT': {2: (1,)},
    'DINT2INTP': {2: (1,)},
    'DINT2UDINT': {2: (1,)},
    'DINT2UDINTP': {2: (1,)},
    'DINT2UINT': {2: (1,)},
    'DINT2UINTP': {2: (1,)},
    'DIS': {3: (1,)},
    'DISP': {3: (1,)},
    'DMOV': {2: (1,)},
    'DMOVP': {2: (1,)},
    'DNEG': {1: (0,)},
    'DNEGP': {1: (0,)},
    'DOR': {2: (1,), 3: (2,)},
    'DORP': {2: (1,), 3: (2,)},
    'DSERDATA': {4: (2,)},
    'DSERDATAP': {4: (2,)},
    'DSERMM': {4: (2,)},
    'DSERMMP': {4: (2,)},
    'DSFL': {2: (0,)},
    'DSFLP': {2: (0,)},
    'DSFR': {2: (0,)},
    'DSFRP': {2: (0,)},
    'DSQRT': {2: (1,)},
    'DSQRTP': {2: (1,)},
    'DSUM': {2: (1,)},
    'DSUMP': {2: (1,)},
    'DSWAP': {1: (0,)},
    'DSWAPP': {1: (0,)},
    'DTEST': {3: (2,)},
    'DTESTP': {3: (2,)},
    'DUTY': {3: (2,)},
    'DWSFTL': {4: (1,)},
    'DWSFTLP': {4: (1,)},
    'DWSFTR': {4: (1,)},
    'DWSFTRP': {4: (1,)},
    'DXCH': {2: (0, 1)},
    'DXCHP': {2: (0, 1)},
    'DXNR': {2: (1,)},
    'DXNRP': {2: (1,)},
    'DXOR': {2: (1,), 3: (2,)},
    'DXORP': {2: (1,), 3: (2,)},
    'E*': {3: (2,)},
    'E*P': {3: (2,)},
    'E+': {2: (1,), 3: (2,)},
    'E+P': {2: (1,), 3: (2,)},
    'E-': {2: (1,), 3: (2,)},
    'E-P': {2: (1,), 3: (2,)},
    'E/': {3: (2,)},
    'E/P': {3: (2,)},
    'ECALL': {3: ()},
    'ECALLP': {3: ()},
    'ECMP': {3: (2,)},
    'ECMPP': {3: (2,)},
    'ED*': {3: (2,)},
    'ED*P': {3: (2,)},
    'ED+': {2: (1,), 3: (2,)},
    'ED+P': {2: (1,), 3: (2,)},
    'ED-': {2: (1,), 3: (2,)},
    'ED-P': {2: (1,), 3: (2,)},
    'ED/': {3: (2,)},
    'ED/P': {3: (2,)},
    'EDCMP': {3: (2,)},
    'EDCMPP': {3: (2,)},
    'EDMAX': {3: (1,)},
    'EDMAXP': {3: (1,)},
    'EDMIN': {3: (1,)},
    'EDMINP': {3: (1,)},
    'EDMOV': {2: (1,)},
    'EDMOVP': {2: (1,)},
    'EDNEG': {1: (0,)},
    'EDNEGP': {1: (0,)},
    'EDSFL': {2: (0,)},
    'EDSFLP': {2: (0,)},
    'EDSFR': {2: (0,)},
    'EDSFRP': {2: (0,)},
    'EDSFTL': {4: (1,)},
    'EDSFTLP': {4: (1,)},
    'EDSFTR': {4: (1,)},
    'EDSFTRP': {4: (1,)},
    'EDSQRT': {2: (1,)},
    'EDSQRTP': {2: (1,)},
    'EDZCP': {4: (3,)},
    'EDZCPP': {4: (3,)},
    'EFCALL': {3: ()},
    'EFCALLP': {3: ()},
    'EMAX': {3: (1,)},
    'EMAXP': {3: (1,)},
    'EMIN': {3: (1,)},
    'EMINP': {3: (1,)},
    'EMOD': {3: (2,)},
    'EMODP': {3: (2,)},
    'EMOV': {2: (1,)},
    'EMOVP': {2: (1,)},
    'ENCO': {3: (1,)},
    'ENCOP': {3: (1,)},
    'ENEG': {1: (0,)},
    'ENEGP': {1: (0,)},
    'EREXP': {3: (2,)},
    'EREXPP': {3: (2,)},
    'ESFL': {2: (0,)},
    'ESFLP': {2: (0,)},
    'ESFR': {2: (0,)},
    'ESFRP': {2: (0,)},
    'ESFTL': {4: (1,)},
    'ESFTLP': {4: (1,)},
    'ESFTR': {4: (1,)},
    'ESFTRP': {4: (1,)},
    'ESQRT': {2: (1,)},
    'ESQRTP': {2: (1,)},
    'ESTR': {3: (2,)},
    'ESTRP': {3: (2,)},
    'EVAL': {2: (1,)},
    'EVALP': {2: (1,)},
    'EXP': {2: (1,)},
    'EXPD': {2: (1,)},
    'EXPDP': {2: (1,)},
    'EXPP': {2: (1,)},
    'EZCP': {4: (3,)},
    'EZCPP': {4: (3,)},
    'FCALL': {2: ()},
    'FCALLP': {2: ()},
    'FDEL': {3: (1,)},
    'FDELP': {3: (1,)},
    'FF': {1: (0,)},
    'FIFR': {2: (1,)},
    'FIFRP': {2: (1,)},
    'FIFW': {2: (1,)},
    'FIFWP': {2: (1,)},
    'FINS': {3: (1,)},
    'FINSP': {3: (1,)},
    'FLT2DBL': {2: (1,)},
    'FLT2DBLP': {2: (1,)},
    'FLT2DINT': {2: (1,)},
    'FLT2DINTP': {2: (1,)},
    'FLT2INT': {2: (1,)},
    'FLT2INTP': {2: (1,)},
    'FLT2UDINT': {2: (1,)},
    'FLT2UDINTP': {2: (1,)},
    'FLT2UINT': {2: (1,)},
    'FLT2UINTP': {2: (1,)},
    'FMOV': {3: (1,)},
    'FMOVL': {3: (1,)},
    'FMOVLP': {3: (1,)},
    'FMOVP': {3: (1,)},
    'FPOP': {2: (1,)},
    'FPOPP': {2: (1,)},
    'G.DNTMRD': {4: (2,)},
    'G.DNTMWR': {4: ()},
    'G.DNTSRD': {4: (2,)},
    'G.DNTSWR': {4: ()},
    'G.INPUT': {4: (2, 3)},
    'G.SOCRCVS': {3: (2,)},
    'GP.CONCLOSE': {4: (3,)},
    'GP.CONOPEN': {4: (3,)},
    'GP.ECPRTCL': {5: (4,)},
    'GP.SOCRCV': {5: (3, 4)},
    'GP.SOCSND': {5: (4,)},
    'HABIN': {2: (1,)},
    'HABINP': {2: (1,)},
    'HOURM': {3: (1, 2)},
    'IMASK': {1: ()},
    'INSTR': {4: (2,)},
    'INSTRP': {4: (2,)},
    'INT2ASC': {3: (1,)},
    'INT2ASCP': {3: (1,)},
    'INT2DBL': {2: (1,)},
    'INT2DBLP': {2: (1,)},
    'INT2DINT': {2: (1,)},
    'INT2DINTP': {2: (1,)},
    'INT2FLT': {2: (1,)},
    'INT2FLTP': {2: (1,)},
    'INT2UDINT': {2: (1,)},
    'INT2UDINTP': {2: (1,)},
    'INT2UINT': {2: (1,)},
    'INT2UINTP': {2: (1,)},
    'JP.REMFRD': {8: (5, 7)},
    'JP.REMTOD': {8: (7,)},
    'LEFT': {3: (1,)},
    'LEFTP': {3: (1,)},
    'LEN': {2: (1,)},
    'LENP': {2: (1,)},
    'LOG': {2: (1,)},
    'LOG10': {2: (1,)},
    'LOG10D': {2: (1,)},
    'LOG10DP': {2: (1,)},
    'LOG10P': {2: (1,)},
    'LOGD': {2: (1,)},
    'LOGDP': {2: (1,)},
    'LOGP': {2: (1,)},
    'LOGTRG': {1: ()},
    'LOGTRGR': {1: ()},
    'MIDR': {3: (1,)},
    'MIDRP': {3: (1,)},
    'MIDW': {3: (1,)},
    'MIDWP': {3: (1,)},
    'MOV': {2: (1,)},
    'MOVB': {2: (1,)},
    'MOVBP': {2: (1,)},
    'MOVP': {2: (1,)},
    'MTR': {4: (1, 2)},
    'NDIS': {3: (1,)},
    'NDISP': {3: (1,)},
    'NEG': {1: (0,)},
    'NEGP': {1: (0,)},
    'NUNI': {3: (1,)},
    'NUNIP': {3: (1,)},
    'OUT': {1: (0,)},
    'PABORT': {1: ()},
    'PALERT': {1: ()},
    'PALERTP': {1: ()},
    'PAUSE': {1: (0,)},
    'PHASE': {1: ()},
    'PHASECHG': {1: (0,)},
    'PID': {4: (3,)},
    'PIDCONT': {1: ()},
    'PIDCONTP': {1: ()},
    'PIDINIT': {1: ()},
    'PIDINITP': {1: ()},
    'PIDPRMW': {2: ()},
    'PIDPRMWP': {2: ()},
    'PIDRUN': {1: ()},
    'PIDRUNP': {1: ()},
    'PIDSTOP': {1: ()},
    'PIDSTOPP': {1: ()},
    'PLF': {1: (0,)},
    'PLS': {1: (0,)},
    'PLSY': {3: (2,)},
    'POFF': {1: ()},
    'POFFP': {1: ()},
    'POW': {3: (2,)},
    'POWD': {3: (2,)},
    'POWDP': {3: (2,)},
    'POWP': {3: (2,)},
    'PSCAN': {1: ()},
    'PSCANP': {1: ()},
    'PSTOP': {1: ()},
    'PSTOPP': {1: ()},
    'PWM': {3: (2,)},
    'QDRSET': {1: ()},
    'QDRSETP': {1: ()},
    'RAD': {2: (1,)},
    'RADD': {2: (1,)},
    'RADDP': {2: (1,)},
    'RADP': {2: (1,)},
    'RAMPQ': {7: (2, 3, 5, 6)},
    'RFS': {2: ()},
    'RFSP': {2: ()},
    'RIGHT': {3: (1,)},
    'RIGHTP': {3: (1,)},
    'RND': {1: (0,)},
    'RNDP': {1: (0,)},
    'ROTC': {13: (5, 6, 7, 8, 9, 10, 11, 12)},
    'RSET': {1: ()},
    'RSETP': {1: ()},
    'RST': {1: (0,)},
    'RSTART': {1: (0,)},
    'S.2PID': {5: (1, 3)},
    'S.<': {4: (1,)},
    'S.<=': {4: (1,)},
    'S.=': {4: (1,)},
    'S.>': {4: (1,)},
    'S.>=': {4: (1,)},
    'S.ABS': {4: (1,)},
    'S.ADD': {4: (1,)},
    'S.AMR': {4: (1,)},
    'S.AT1': {5: (1, 3, 4)},
    'S.AVE': {4: (1,)},
    'S.BC': {4: (1, 3)},
    'S.BPI': {5: (1, 3)},
    'S.BUMP': {4: (1, 3)},
    'S.D': {4: (1, 3)},
    'S.DBND': {4: (1,)},
    'S.DED': {4: (1, 3)},
    'S.DIV': {4: (1,)},
    'S.DUTY': {4: (1, 3)},
    'S.ENG': {4: (1,)},
    'S.FG': {4: (1, 3)},
    'S.FLT': {4: (1, 3)},
    'S.HS': {4: (1,)},
    'S.I': {4: (1,)},
    'S.IENG': {4: (1,)},
    'S.IFG': {4: (1, 3)},
    'S.IN': {4: (1, 3)},
    'S.IPD': {5: (1, 3)},
    'S.LIMT': {4: (1,)},
    'S.LLAG': {4: (1, 3)},
    'S.LS': {4: (1,)},
    'S.MID': {4: (1,)},
    'S.MOUT': {4: (1, 3)},
    'S.MUL': {4: (1,)},
    'S.ONF2': {5: (1, 3)},
    'S.ONF3': {5: (1, 3)},
    'S.OUT1': {4: (1, 3)},
    'S.OUT2': {4: (1, 3)},
    'S.PGS': {4: (1, 3)},
    'S.PHPL': {4: (1, 3)},
    'S.PHPL2': {4: (1, 3)},
    'S.PID': {5: (1, 3)},
    'S.PIDP': {5: (1, 3)},
    'S.PSUM': {4: (1, 3)},
    'S.R': {5: (1, 3)},
    'S.SEL': {5: (1, 3)},
    'S.SOCRCVS': {3: (2,)},
    'S.SPI': {5: (1, 3)},
    'S.SQR': {4: (1,)},
    'S.SUB': {4: (1,)},
    'S.SUM': {4: (1,)},
    'S.TPC': {4: (1,)},
    'S.VLMT1': {4: (1,)},
    'S.VLMT2': {4: (1,)},
    'SEC2TIME': {2: (1,)},
    'SEC2TIMEP': {2: (1,)},
    'SEG': {2: (1,)},
    'SEGP': {2: (1,)},
    'SERDATA': {4: (2,)},
    'SERDATAP': {4: (2,)},
    'SERMM': {4: (2,)},
    'SERMMP': {4: (2,)},
    'SET': {1: (0,)},
    'SFL': {2: (0,)},
    'SFLP': {2: (0,)},
    'SFR': {2: (0,)},
    'SFRP': {2: (0,)},
    'SFT': {1: (0,)},
    'SFTBL': {3: (0,)},
    'SFTBLP': {3: (0,)},
    'SFTBR': {3: (0,)},
    'SFTBRP': {3: (0,)},
    'SFTDWL': {3: (0,)},
    'SFTDWLP': {3: (0,)},
    'SFTDWR': {3: (0,)},
    'SFTDWRP': {3: (0,)},
    'SFTEDL': {3: (0,)},
    'SFTEDLP': {3: (0,)},
    'SFTEDR': {3: (0,)},
    'SFTEDRP': {3: (0,)},
    'SFTEL': {3: (0,)},
    'SFTELP': {3: (0,)},
    'SFTER': {3: (0,)},
    'SFTERP': {3: (0,)},
    'SFTL': {4: (1,)},
    'SFTLP': {4: (1,)},
    'SFTP': {1: (0,)},
    'SFTR': {4: (1,)},
    'SFTRP': {4: (1,)},
    'SFTWL': {3: (0,)},
    'SFTWLP': {3: (0,)},
    'SFTWR': {3: (0,)},
    'SFTWRP': {3: (0,)},
    'SIMASK': {2: ()},
    'SIN': {2: (1,)},
    'SIND': {2: (1,)},
    'SINDP': {2: (1,)},
    'SINP': {2: (1,)},
    'SJIS2WS': {2: (1,)},
    'SJIS2WSB': {2: (1,)},
    'SJIS2WSBP': {2: (1,)},
    'SJIS2WSP': {2: (1,)},
    'SMOV': {5: (3,)},
    'SMOVP': {5: (3,)},
    'SP.CONTSW': {2: (1,)},
    'SP.DEVST': {4: (3,)},
    'SP.ECPRTCL': {5: (4,)},
    'SP.FCOPY': {7: (1, 6)},
    'SP.FDELETE': {5: (2, 4)},
    'SP.FMOVE': {7: (1, 6)},
    'SP.FREAD': {6: (2, 4, 5)},
    'SP.FRENAME': {6: (2, 5)},
    'SP.FSTATUS': {6: (2, 4, 5)},
    'SP.FTPGET': {5: (4,)},
    'SP.FTPPUT': {5: (4,)},
    'SP.FWRITE': {6: (2, 5)},
    'SP.SIDRD': {4: (1, 2, 3)},
    'SP.SLMPSND': {5: (3, 4)},
    'SP.SOCCINF': {4: (3,)},
    'SP.SOCCLOSE': {4: (3,)},
    'SP.SOCCSET': {3: ()},
    'SP.SOCOPEN': {4: (3,)},
    'SP.SOCRCV': {5: (3, 4)},
    'SP.SOCRMODE': {3: ()},
    'SP.SOCSND': {5: (4,)},
    'SPD': {3: (2,)},
    'SQRT': {2: (1,)},
    'SQRTP': {2: (1,)},
    'SRND': {1: ()},
    'SRNDP': {1: ()},
    'STMR': {6: (2, 3, 4, 5)},
    'STRDEL': {3: (0,)},
    'STRDELP': {3: (0,)},
    'STRINS': {3: (1,)},
    'STRINSP': {3: (1,)},
    'SUM': {2: (1,)},
    'SUMP': {2: (1,)},
    'SWAP': {1: (0,)},
    'SWAPP': {1: (0,)},
    'TAN': {2: (1,)},
    'TAND': {2: (1,)},
    'TANDP': {2: (1,)},
    'TANP': {2: (1,)},
    'TCMP': {5: (4,)},
    'TCMPP': {5: (4,)},
    'TEST': {3: (2,)},
    'TESTP': {3: (2,)},
    'TIMCHK': {3: (2,)},
    'TIME2SEC': {2: (1,)},
    'TIME2SECP': {2: (1,)},
    'TTMR': {3: (0, 1)},
    'TYPERD': {2: (1,)},
    'TYPERDP': {2: (1,)},
    'TZCP': {4: (3,)},
    'TZCPP': {4: (3,)},
    'UDCNT1': {4: (2,)},
    'UDCNT2': {4: (2,)},
    'UDINT2DBL': {2: (1,)},
    'UDINT2DBLP': {2: (1,)},
    'UDINT2DINT': {2: (1,)},
    'UDINT2DINTP': {2: (1,)},
    'UDINT2FLT': {2: (1,)},
    'UDINT2FLTP': {2: (1,)},
    'UDINT2INT': {2: (1,)},
    'UDINT2INTP': {2: (1,)},
    'UDINT2UINT': {2: (1,)},
    'UDINT2UINTP': {2: (1,)},
    'UINT2DBL': {2: (1,)},
    'UINT2DBLP': {2: (1,)},
    'UINT2DINT': {2: (1,)},
    'UINT2DINTP': {2: (1,)},
    'UINT2FLT': {2: (1,)},
    'UINT2FLTP': {2: (1,)},
    'UINT2INT': {2: (1,)},
    'UINT2INTP': {2: (1,)},
    'UINT2UDINT': {2: (1,)},
    'UINT2UDINTP': {2: (1,)},
    'UNI': {3: (1,)},
    'UNIINFRD': {3: (1,)},
    'UNIINFRDP': {3: (1,)},
    'UNIP': {3: (1,)},
    'WAND': {2: (1,), 3: (2,)},
    'WANDP': {2: (1,), 3: (2,)},
    'WOR': {2: (1,), 3: (2,)},
    'WORP': {2: (1,), 3: (2,)},
    'WS2SJIS': {2: (1,)},
    'WS2SJISP': {2: (1,)},
    'WSFL': {4: (1,)},
    'WSFLP': {4: (1,)},
    'WSFR': {4: (1,)},
    'WSFRP': {4: (1,)},
    'WTOB': {3: (1,)},
    'WTOBP': {3: (1,)},
    'WXNR': {2: (1,)},
    'WXNRP': {2: (1,)},
    'WXOR': {2: (1,), 3: (2,)},
    'WXORP': {2: (1,), 3: (2,)},
    'XCALL': {2: ()},
    'XCH': {2: (0, 1)},
    'XCHP': {2: (0, 1)},
    'Z.BUFRCVS': {3: (2,)},
    'ZP.CSET': {5: (3, 4)},
    'ZP.UINI': {3: (2,)},
    'ZPOP': {3: (0, 2)},
    'ZPOPP': {3: (0, 2)},
    'ZPUSH': {3: (0, 2)},
    'ZPUSHP': {3: (0, 2)},
    'ZRRDB': {2: (1,)},
    'ZRRDBP': {2: (1,)},
    'ZRWRB': {2: ()},
    'ZRWRBP': {2: ()},
}


def manual_write_indices(opcode: str, argc: int) -> set[int] | None:
    """Destination operand positions for opcode at this operand count.

    None when the manuals do not pin it down, so the caller can fall back.
    """
    entry = MANUAL_WRITE_ARGS.get(opcode)
    if entry is None:
        return None
    indices = entry.get(argc)
    if indices is None:
        return None
    return set(indices)
