from __future__ import annotations

"""Submit a redacted support report to GitHub Issues."""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
import zipfile
from pathlib import Path

from gx3cli.gx3_project_paths import default_project_root, resolve_project_root
from gx3cli.gx3_support_bundle import build_bundle, default_output, redactor
from gx3cli.gx3_version import package_version


DEFAULT_REPOSITORY = "purinzan/gx3-cli-mcp"
DEFAULT_BODY_CHARS = 50000
DEFAULT_SECTION_CHARS = 12000


def timestamp() -> str:
    return time.strftime("%Y%m%d_%H%M%S")


def default_body_output() -> str:
    return f"gx3_support_report_{timestamp()}.md"


def read_optional_text(path: Path | None) -> str:
    if path is None:
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def clip_text(text: str, max_chars: int) -> str:
    if len(text) <= max_chars:
        return text
    marker = f"\n\n[truncated: {len(text)} chars total]\n\n"
    head = max_chars // 2
    tail = max_chars - head - len(marker)
    if tail <= 0:
        return text[:max_chars]
    return text[:head] + marker + text[-tail:]


def zip_text(bundle: Path, name: str) -> str:
    with zipfile.ZipFile(bundle) as zf:
        try:
            data = zf.read(name)
        except KeyError:
            return ""
    return data.decode("utf-8", errors="replace")


def zip_manifest(bundle: Path) -> dict[str, object]:
    text = zip_text(bundle, "manifest.json")
    if not text:
        return {}
    try:
        value = json.loads(text)
    except json.JSONDecodeError:
        return {}
    return value if isinstance(value, dict) else {}


def build_issue_body(
    root: Path,
    bundle: Path,
    *,
    command: str = "",
    message: str = "",
    error_text: str = "",
    max_chars: int = DEFAULT_BODY_CHARS,
) -> str:
    root = resolve_project_root(root)
    manifest = zip_manifest(bundle)
    doctor = zip_text(bundle, "doctor.txt").strip()
    parse_gap_summary = zip_text(bundle, "parse_gap_summary_redacted.json").strip()
    _table, redact = redactor(root)

    user_message = redact(message.strip()) if message.strip() else "(not provided)"
    attempted_command = redact(command.strip()) if command.strip() else "(not provided)"
    captured_error = redact(error_text.strip()) if error_text.strip() else "(not provided)"

    body = "\n".join(
        [
            "<!-- Generated by gx3-cli report-issue. Redacted diagnostic summary only. -->",
            "",
            "## Support Request",
            "",
            f"- gx3-cli-mcp version: {manifest.get('package_version') or package_version()}",
            f"- Python: {manifest.get('python') or ''}",
            f"- Platform: {manifest.get('platform') or ''}",
            f"- Bundle schema: {manifest.get('bundle_schema') or ''}",
            f"- Local bundle file: `{bundle.name}` (not uploaded by this command)",
            "",
            "## User Message",
            "",
            user_message,
            "",
            "## Command Tried",
            "",
            "```text",
            attempted_command,
            "```",
            "",
            "## Error Or Symptom",
            "",
            "```text",
            captured_error,
            "```",
            "",
            "## Parse Gap Summary",
            "",
            "```json",
            clip_text(parse_gap_summary or "{}", DEFAULT_SECTION_CHARS),
            "```",
            "",
            "## Doctor",
            "",
            "```text",
            clip_text(doctor or "(doctor output missing)", DEFAULT_SECTION_CHARS),
            "```",
            "",
            "## Privacy",
            "",
            "- The attached project file is not uploaded.",
            "- Ladder body data is not included.",
            "- Project paths, IP addresses, comments, POU names, and Japanese text are pseudonymized when detected.",
            "- The local alias table is not included.",
            "",
        ]
    )
    return redact(clip_text(body, max_chars))


def github_token() -> str:
    return os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN") or ""


def submit_issue_api(repo: str, title: str, body: str, token: str) -> str:
    payload = json.dumps({"title": title, "body": body}).encode("utf-8")
    request = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/issues",
        data=payload,
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "User-Agent": "gx3-cli-mcp",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            data = json.loads(response.read().decode("utf-8", errors="replace"))
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"GitHub API rejected the report: HTTP {exc.code}: {detail}") from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"GitHub API request failed: {exc.reason}") from exc
    url = str(data.get("html_url") or "")
    if not url:
        raise RuntimeError("GitHub API response did not include issue URL")
    return url


def submit_issue_gh(repo: str, title: str, body: str) -> str:
    gh = shutil.which("gh")
    if not gh:
        raise RuntimeError("GitHub CLI `gh` is not installed")
    body_file = Path(tempfile.gettempdir()) / f"gx3_report_issue_{os.getpid()}_{timestamp()}.md"
    body_file.write_text(body, encoding="utf-8")
    try:
        completed = subprocess.run(
            [gh, "issue", "create", "--repo", repo, "--title", title, "--body-file", str(body_file)],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
        )
    finally:
        try:
            body_file.unlink()
        except OSError:
            pass
    if completed.returncode != 0:
        detail = "\n".join(part for part in [completed.stdout.strip(), completed.stderr.strip()] if part)
        raise RuntimeError(f"GitHub CLI could not create the issue: {detail}")
    for line in completed.stdout.splitlines():
        if line.startswith("https://"):
            return line.strip()
    return completed.stdout.strip()


def submit_issue(repo: str, title: str, body: str) -> str:
    errors: list[str] = []
    token = github_token()
    if token:
        try:
            return submit_issue_api(repo, title, body, token)
        except RuntimeError as exc:
            errors.append(str(exc))
    if shutil.which("gh"):
        try:
            return submit_issue_gh(repo, title, body)
        except RuntimeError as exc:
            errors.append(str(exc))
    hint = "Set GH_TOKEN/GITHUB_TOKEN or install and authenticate GitHub CLI with `gh auth login`."
    if errors:
        raise RuntimeError("Could not submit report.\n" + "\n".join(errors) + "\n" + hint)
    raise RuntimeError("Could not submit report. " + hint)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Create a redacted support bundle and submit a GitHub issue report."
    )
    parser.add_argument("--root", default=str(default_project_root()), help="extracted project folder or .gx3")
    parser.add_argument("--repo", default=DEFAULT_REPOSITORY, help="GitHub repo owner/name")
    parser.add_argument("--title", default="GX3 support report", help="GitHub issue title")
    parser.add_argument("--message", default="", help="short user-visible problem description")
    parser.add_argument("--message-file", type=Path, help="read problem description from a UTF-8 text file")
    parser.add_argument("--command", default="", help="command that failed or produced confusing output")
    parser.add_argument("--error-file", type=Path, help="read error output or symptom details from a UTF-8 text file")
    parser.add_argument("-o", "--output", default=default_output(), help="local redacted support ZIP path")
    parser.add_argument("--body-output", default=default_body_output(), help="local issue body Markdown path")
    parser.add_argument("--dry-run", action="store_true", help="create local files but do not submit to GitHub")
    parser.add_argument("--yes", action="store_true", help="submit the redacted report without an interactive prompt")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = resolve_project_root(args.root)
    message = "\n".join(part for part in [args.message, read_optional_text(args.message_file)] if part).strip()
    error_text = read_optional_text(args.error_file)

    bundle = build_bundle(root, Path(args.output))
    body = build_issue_body(root, bundle, command=args.command, message=message, error_text=error_text)
    body_path = Path(args.body_output)
    body_path.parent.mkdir(parents=True, exist_ok=True)
    body_path.write_text(body, encoding="utf-8")

    print(f"support bundle: {bundle}")
    print(f"issue body: {body_path}")
    if args.dry_run:
        print("dry run: GitHub issue was not submitted")
        return 0
    if not args.yes:
        print("report not submitted: re-run with --yes after reviewing the issue body", file=sys.stderr)
        return 2
    try:
        url = submit_issue(args.repo, args.title, body)
    except RuntimeError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    print(f"issue submitted: {url}")
    return 0


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    raise SystemExit(main())
